version: "3.8"

services:
  web:
    build: .
    container_name: warranty_register
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn warranty_core.wsgi:application --bind 0.0.0.0:8000 --workers=3
      "
    volumes:
      - ./:/app

    restart: unless-stopped
    networks:
      - app_network

volumes:
  static_volume:
   - static_volume:/app/staticfiles
networks:
  app_network:
    driver: bridge
