version: "3.8"

services:
  web:
    env_file:
      - .env.pg
    depends_on:
      - db
    command: >
      sh -c "
        until pg_isready -h db -p 5432 -U postgres; do
          echo 'Waiting for database...';
          sleep 1;
        done &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn warranty_core.wsgi:application --bind 0.0.0.0:8000 --workers=3
      "

  db:
    image: postgres:13
    container_name: warranty_register_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: warranty_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - app_network
    restart: unless-stopped

volumes:
  pgdata:
